# Site settings
title: Biostatistics Graduate Student Association (BSGSA)
email: contact@bsgsa.berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  The Biostatistics Graduate Student Association (BSGSA) is
  a student organization at UC Berkeley. Our goal is to represent
  the interests and needs of graduate students in biostatistics.
disclaimer: > # this means to ignore newlines until "baseurl:"
  We are a student group acting independently of the University of California.
  We take full responsibility for our organization and this web site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bsgsa.berkeley.edu" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_username:  UCBerkeleybiostatistics

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
